const quizTypes = {
  SET_TYPE_OF_QUIZ: 'SET_TYPE_OF_QUIZ',
  CREATE_FIRST_QUESTION_INIT: 'CREATE_FIRST_QUESTION_INIT',
  CREATE_FIRST_QUESTION_SUCCESS: 'CREATE_FIRST_QUESTION_SUCCESS',
  CREATE_FIRST_QUESTION_ERROR: 'CREATE_FIRST_QUESTION_ERROR',
  SELECT_ANSWER: 'SELECT_ANSWER',
  SET_IS_CHECKING_ANSWER: 'SET_IS_CHECKING_ANSWER',
  INCREMENT_SCORE: 'INCREMENT_SCORE',
  CREATE_NEW_QUESTION_INIT: 'CREATE_NEW_QUESTION_INIT',
  CREATE_NEW_QUESTION_SUCCESS: 'CREATE_NEW_QUESTION_SUCCESS',
  RESET_QUIZ_STATE: 'RESET_QUIZ_STATE'
}

export default quizTypes;