const quizTypes = {
  SET_QUIZ_TYPE: 'SET_QUIZ_TYPE',
  SET_REGION: 'SET_REGION',
  GET_QUIZ_QUESTIONS_INIT: 'GET_QUIZ_QUESTIONS_INIT',
  GET_QUIZ_QUESTIONS_SUCCESS: 'GET_QUIZ_QUESTIONS_SUCCESS',
  GET_QUIZ_QUESTIONS_ERROR: 'GET_QUIZ_QUESTIONS_ERROR',
  SELECT_ANSWER: 'SELECT_ANSWER',
  CHECK_ANSWER_INIT: 'CHECK_ANSWER_INIT',
  CREATE_NEW_QUESTION: 'CREATE_NEW_QUESTION',
  CHECK_ANSWER_SUCCESS: 'CHECK_ANSWER_SUCCESS',
  CHECK_ANSWER_ERROR: 'CHECK_ANSWER_ERROR',
  RESET_QUIZ_STATE: 'RESET_QUIZ_STATE'
}

export default quizTypes;